# Generated by Django 3.0.9 on 2020-11-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='file',
            new_name='data_file',
        ),
    ]
