# Generated by Django 3.0.9 on 2020-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201113_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_file',
            field=models.FileField(upload_to='datasets'),
        ),
    ]
